# Generated by Django 3.2.5 on 2022-01-31 07:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obtained_date', models.DateField(blank=True, null=True)),
                ('made_by', models.CharField(blank=True, max_length=400, null=True)),
                ('SMILES', models.CharField(blank=True, max_length=400, null=True)),
                ('commercial', models.BooleanField(default=True)),
                ('opened_under_air', models.BooleanField(default=True)),
                ('disposed', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('URL', models.CharField(blank=True, max_length=400, null=True)),
                ('cris_id', models.CharField(blank=True, max_length=200, null=True)),
                ('room', models.CharField(blank=True, max_length=200, null=True)),
                ('memo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chemical',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experimenter', models.CharField(max_length=200)),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Experiment date')),
                ('bookmark', models.BooleanField(default=False)),
                ('machine_learning', models.BooleanField(default=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obtained_date', models.DateField(blank=True, null=True)),
                ('made_by', models.CharField(blank=True, max_length=400, null=True)),
                ('commercial', models.BooleanField(default=False)),
                ('disposed', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('URL', models.CharField(blank=True, max_length=400, null=True)),
                ('room', models.CharField(blank=True, max_length=200, null=True)),
                ('memo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MutualKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('memo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MutualKey',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('memo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Mixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expmanager.mixture')),
                ('chemical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expmanager.chemical')),
                ('fusion_experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fusion_experiment', to='expmanager.experiment')),
                ('insert_experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insert_experiment', to='expmanager.experiment')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='expmanager.experiment')),
                ('mutual_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutual_key', to='expmanager.mutualkey')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_Mixture', to='expmanager.mixture')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_Mixture_title', to='expmanager.propertyname')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyChem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_chem', to='expmanager.chemical')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_chem_title', to='expmanager.propertyname')),
            ],
            options={
                'verbose_name': 'PropertyChem',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='expmanager.step')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_title', to='expmanager.propertyname')),
            ],
        ),
        migrations.CreateModel(
            name='MixtureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='user_files/others')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mixture_file', to='expmanager.mixture')),
            ],
        ),
        migrations.CreateModel(
            name='MixtureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('mol_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('wt_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('vol_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_c', to='expmanager.chemical')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mixture_c', to='expmanager.mixture')),
            ],
        ),
        migrations.AddField(
            model_name='mixture',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='expmanager.Tag'),
        ),
        migrations.CreateModel(
            name='ExperimentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='user_files/others')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_file', to='expmanager.experiment')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_name', to='expmanager.project'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='expmanager.Tag'),
        ),
        migrations.CreateModel(
            name='ChemicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='user_files/others')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_file', to='expmanager.chemical')),
            ],
        ),
        migrations.AddField(
            model_name='chemical',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='expmanager.Tag'),
        ),
    ]
