# Generated by Django 3.2.5 on 2022-01-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
