# Generated by Django 3.2.5 on 2022-02-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0002_chemical_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'verbose_name': 'Experiment'},
        ),
        migrations.AlterModelOptions(
            name='mixture',
            options={'verbose_name': 'Mixture'},
        ),
    ]
