# Generated by Django 3.2.5 on 2022-02-03 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0003_auto_20220201_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='opened_under_air',
        ),
    ]
