# Generated by Django 3.2.5 on 2022-02-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0005_auto_20220203_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemical',
            old_name='memo',
            new_name='special_memo',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='content',
            new_name='special_content',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='memo',
            new_name='special_memo',
        ),
        migrations.RenameField(
            model_name='mixture',
            old_name='memo',
            new_name='special_memo',
        ),
        migrations.RenameField(
            model_name='mutualkey',
            old_name='memo',
            new_name='special_memo',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='memo',
            new_name='special_memo',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='memo',
            new_name='special_memo',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='machine_learning',
        ),
    ]
