# Generated by Django 3.2.5 on 2022-02-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0006_auto_20220203_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixturecomponent',
            name='molar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
