# Generated by Django 3.2.5 on 2022-02-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0008_alter_property_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyname',
            name='explanation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
