# Generated by Django 3.1.2 on 2022-02-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0010_auto_20220208_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='SMILES',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
