# Generated by Django 3.1.2 on 2022-02-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0012_auto_20220211_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='special_memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
