# Generated by Django 3.1.2 on 2022-03-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0013_tag_special_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='special_memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertychem',
            name='special_memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertymixture',
            name='special_memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
