# Generated by Django 3.1.2 on 2022-03-04 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0014_auto_20220304_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_name', to='expmanager.project'),
        ),
    ]
