# Generated by Django 3.1.2 on 2022-03-04 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0015_auto_20220304_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_name', to='expmanager.project'),
        ),
    ]
