# Generated by Django 3.1.2 on 2022-03-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expmanager', '0016_auto_20220304_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='SMILES',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
    ]
